name: "Gradle build"
permissions:
  contents: write
  id-token: write
  attestations: write
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: "Gradle build Debug"
    runs-on: ubuntu-latest
    env:
      GRADLE_MICROG_VERSION_WITHOUT_GIT: 1

    steps:
      - name: "Free disk space"
        run: |
          # Deleting unneeded software packages
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /opt/hostedtoolcache/go

          # Log available space
          df -h
      - name: "Checkout sources"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: "Setup Java"
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
      - name: "Setup matchers"
        run: |
          # Setting up matchers...

          matchers_dir='${{ github.workspace }}/.github/matchers'
          matcher_list()
          {
            echo 'gradle-build-matcher.json'
            echo 'gradle-build-kotlin-error-matcher.json'
          }

          matcher_list | while IFS='' read -r NAME; do
            if test -f "${matchers_dir:?}/${NAME:?}"; then
              echo "::add-matcher::${matchers_dir:?}/${NAME:?}"
              echo "Matcher configured: ${NAME:?}"
            fi
          done
      - name: "Execute Gradle assemble"
        run: "./gradlew assembleDebug"
      - name: "Execute Gradle lint"
        run: "./gradlew lintDebug"
      - name: "Collect APK metadata"
        id: apk_meta
        shell: bash
        run: |
          apk_path="$(ls play-services-core/build/outputs/apk/mapboxUser/debug/app.revanced.android.gms-*.apk | head -n1)"
          sha256="$(sha256sum "$apk_path" | awk '{print $1}')"
          echo "apk_path=$apk_path" >> "$GITHUB_OUTPUT"
          echo "sha256=$sha256" >> "$GITHUB_OUTPUT"
      - name: "Generate artifact attestation"
        uses: actions/attest@v4
        with:
          subject-path: "${{ steps.apk_meta.outputs.apk_path }}"
      - name: "Upload ReVanced GmsCore APK"
        uses: actions/upload-artifact@v4
        with:
          name: "gmscore-pkg-rename-artifact"
          path: "${{ steps.apk_meta.outputs.apk_path }}"
          if-no-files-found: error
      - name: "Publish GitHub pre-release"
        if: github.event_name != 'pull_request' && github.ref_name == 'ci-artifact-helper'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.apk_meta.outputs.apk_path }}"
          artifactErrorsFailBuild: true
          prerelease: true
          tag: "gmscore-pkg-rename-test-${{ github.run_number }}-${{ github.run_attempt }}"
          name: "gmscore-pkg-rename build 7dafecf"
          body: |
            Test build for the `gmscore-pkg-rename` branch (built from commit [7dafecf](https://github.com/ReVanced/GmsCore/commit/7dafecff49415db0c3ca773311d855a84e94b6ed))

            Github Action build:
            https://github.com/zappybiby/GmsCore/actions/runs/${{ github.run_id }}

            SHA-256:
            `${{ steps.apk_meta.outputs.sha256 }}`

            Changes in this build:
            Fixes:
            - Fixes ReVanced YT Music connecting to Android Auto.
            - Push notifications for both ReVanced YouTube and ReVanced YT Music should now work.

            Changes:
            Updates package call site resolution paths to correctly target the renamed ReVanced CoreGms package in side-by-side install scenarios.

            Install notes:
            - **If you already have ReVanced CoreGms installed, uninstall it (Look for "microG Services" in installed apps) first before installing this build.**
